name: projeto

services:
  
  api:
    build:
      context: ./api
    environment:
      HELLO_MESSAGE: ${HELLO_MESSAGE:-projeto}

  web:
    build:
      context: ./web
    depends_on:
      - api
    deploy:
      mode: replicated
      replicas: 1
